// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjnsophqfxiamgjxnlls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqbnNvcGhxZnhpYW1nanhubGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MjkyNjMsImV4cCI6MjA4OTUwNTI2M30.TBbIzMbSclL4QV41WZprLT17q9fE7Bxfwr7HcDqiXxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});